### ISSUE TITLE
Multiple Event Same Day

### ISSUE THREAD

**Issue by n04x** [jujumuncher/caleandar#8]
It seems that if I have 2 events in the same day, the second one override the first one...

**Comment by n04x** [comment]
In fact, after further test, both are shown but they are laying on top of each other instead of dividing properly.

**Comment by n04x** [comment]
I solved it, added a new css: 
.calendar-title:nth-child(n) in it example:

```
.cld-title:nth-child(n+2) {
    top: 60px;
}
.cld-title:nth-child(n+3) {
    top: 85px;
}
```
Ans so on...

**Comment by wolffe** [comment]
I solved it by giving the title relative positioning and floating the `.cld-title` right. It's hacky for now, but I intend to rewrite it using Flex CSS.
